In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
def initialize_parameters(layer_dims):                    # here we have to give the architecture 
                                                          # we have to input here number of nodes in layer 
    np.random.seed(3)                 # like 2 features cgpa and profile_score (input layer) for that 2 biases (in hidden layer) 
    parameters = {}                   # 1 bias at output layer so my layer_dims in this case is [2,2,1]
    L = len(layer_dims)         

    for l in range(1, L):

        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      

    return parameters

In [5]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [6]:
def linear_forward(A_prev, W, b):    
    Z = np.dot(W.T, A_prev) + b
    return Z

In [7]:
# Forward Prop
def L_layer_forward(X, parameters):
    A = X
    L = len(parameters) // 2                  # number of layers in the neural network

    
    for l in range(1, L+1):
        A_prev = A 
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
#         print("A"+str(l-1)+": ", A_prev)
#         print("W"+str(l)+": ", Wl)
#         print("b"+str(l)+": ", bl)
#         print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
#     print("A"+str(l)+": ", A)
#     print("**"*20)
    return A,A_prev

In [8]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

In [9]:
 y_hat = y_hat[0][0]

In [10]:
A1

array([[8],
       [8]], dtype=int64)

In [11]:
def update_parameters(parameters,y,y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [12]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.10531456, 0.10531456],
        [0.10531456, 0.10531456]]),
 'b1': array([[0.00066432],
        [0.00066432]]),
 'W2': array([[0.1384],
        [0.1384]]),
 'b2': array([[0.1432]])}

In [13]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.111803  , 0.11365684],
        [0.11219401, 0.11415956]]),
 'b1': array([[0.00159124],
        [0.0016471 ]]),
 'W2': array([[0.1753936],
        [0.1859632]]),
 'b2': array([[0.191248]])}

In [14]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.11910821, 0.12583219],
        [0.12067218, 0.12828986]]),
 'b1': array([[0.00280877],
        [0.00306013]]),
 'W2': array([[0.2101547 ],
        [0.24389837]]),
 'b2': array([[0.24969188]])}

In [15]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.1257041 , 0.14166232],
        [0.12928005, 0.14894873]]),
 'b1': array([[0.00412795],
        [0.0047817 ]]),
 'W2': array([[0.23788224],
        [0.31044447]]),
 'b2': array([[0.31598998]])}

In [16]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 25

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  7.205413203742441
Epoch -  2 Loss -  1.0733686445728834
Epoch -  3 Loss -  0.9583801635331537
Epoch -  4 Loss -  0.9721506091746084
Epoch -  5 Loss -  0.9426118575983916
Epoch -  6 Loss -  0.9001561889946194
Epoch -  7 Loss -  0.8562395613931871
Epoch -  8 Loss -  0.813754659635432
Epoch -  9 Loss -  0.7733115003785209
Epoch -  10 Loss -  0.7349655914480541
Epoch -  11 Loss -  0.6986440529883167
Epoch -  12 Loss -  0.6642479287554847
Epoch -  13 Loss -  0.6316764162404747
Epoch -  14 Loss -  0.6008324193552801
Epoch -  15 Loss -  0.5716236511675292
Epoch -  16 Loss -  0.5439626859081297
Epoch -  17 Loss -  0.5177667714541684
Epoch -  18 Loss -  0.49295759539182915
Epoch -  19 Loss -  0.4694610501917268
Epoch -  20 Loss -  0.44720700781999134
Epoch -  21 Loss -  0.42612910572999907
Epoch -  22 Loss -  0.4061645442068723
Epoch -  23 Loss -  0.3872538945923119
Epoch -  24 Loss -  0.3693409178362933
Epoch -  25 Loss -  0.35237239282656535


{'W1': array([[0.10591591, 0.1826465 ],
        [0.0626126 , 0.23204102]]),
 'b1': array([[0.00506125],
        [0.00485239]]),
 'W2': array([[0.06641936],
        [0.49043874]]),
 'b2': array([[0.49135158]])}

# Using KERAS LIBLARY

In [17]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [18]:
model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1, activation='linear'))

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model.get_weights()

[array([[-0.14074111, -0.38213682],
        [-0.03082371,  0.45004857]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.0101999],
        [-1.1842897]], dtype=float32),
 array([0.], dtype=float32)]

In [21]:
new_weights=[np.array([[0.1 ,0.1],[0.1 ,0.1]]),        # for initial weight keras select randomly but we choose this bcz in manual cal we choose this weights and bias
             np.array([0., 0.]),
             np.array([[0.1],[0.1]]),
             np.array([0.])]                    # for similarity pupose


In [22]:
model.set_weights(new_weights)

In [23]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [24]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [31]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 0s 6ms/step - loss: 1.6221
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 1.6084
Epoch 3/75
4/4 [==============================] - 0s 6ms/step - loss: 1.6026
Epoch 4/75
4/4 [==============================] - 0s 5ms/step - loss: 1.5960
Epoch 5/75
4/4 [==============================] - 0s 5ms/step - loss: 1.6000
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 1.5855
Epoch 7/75
4/4 [==============================] - 0s 5ms/step - loss: 1.5787
Epoch 8/75
4/4 [==============================] - 0s 5ms/step - loss: 1.5725
Epoch 9/75
4/4 [==============================] - 0s 5ms/step - loss: 1.5657
Epoch 10/75
4/4 [==============================] - 0s 5ms/step - loss: 1.5615
Epoch 11/75
4/4 [==============================] - 0s 5ms/step - loss: 1.5566
Epoch 12/75
4/4 [==============================] - 0s 5ms/step - loss: 1.5502
Epoch 13/75
4/4 [==============================] - 0s 4ms/step - loss: 1.

# Using Model Random weights value- but Run one at a time like use model initialize weight otherwise updated weight

In [26]:
model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1, activation='linear'))

In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
model.get_weights()

[array([[ 0.01571524, -0.06828582],
        [-0.30865538,  0.04920208]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.2494186],
        [1.0717083]], dtype=float32),
 array([0.], dtype=float32)]

In [29]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [32]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=100,verbose=1,batch_size=1)

Epoch 1/100
4/4 [==============================] - 0s 5ms/step - loss: 1.2900
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 1.2840
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 1.2830
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 1.2779
Epoch 5/100
4/4 [==============================] - 0s 5ms/step - loss: 1.2740
Epoch 6/100
4/4 [==============================] - 0s 6ms/step - loss: 1.2675
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 1.2675
Epoch 8/100
4/4 [==============================] - 0s 5ms/step - loss: 1.2647
Epoch 9/100
4/4 [==============================] - 0s 5ms/step - loss: 1.2576
Epoch 10/100
4/4 [==============================] - 0s 5ms/step - loss: 1.2561
Epoch 11/100
4/4 [==============================] - 0s 2ms/step - loss: 1.2474
Epoch 12/100
4/4 [==============================] - 0s 5ms/step - loss: 1.2444
Epoch 13/100
4/4 [==============================] - 0s 5ms/st